- name: "Getting python version"
  shell:
    cmd: python3 --version 2>&1 | grep -Po '(?<=Python )(.+)'
  register: python_version

- name: "Checking minimum python version"
  when: python_version.stdout is version("{{ requirements.minimum_python_version }}", '<')
  fail:
    msg: "Minimum python version is {{ requirements.minimum_python_version }} and the currently installed version is {{ python_version.stdout }}"